import type { VercelRequest, VercelResponse } from '@vercel/node';
import { sql, initSchema } from './_db.js';

const INITIAL_MEMBERS = [
  { id: 'm1', name: 'Ankur' },
  { id: 'm2', name: 'Harith' },
  { id: 'm3', name: 'Kislay' },
  { id: 'm4', name: 'Ankit' },
  { id: 'm5', name: 'Abhinav' },
  { id: 'm6', name: 'AJ' },
  { id: 'm7', name: 'Abhinav 2' },
  { id: 'm8', name: 'Akhil' },
  { id: 'm9', name: 'Akshay' },
  { id: 'm10', name: 'Alok' },
  { id: 'm11', name: 'Aman' },
  { id: 'm12', name: 'Amey' },
  { id: 'm13', name: 'Ananya' },
  { id: 'm14', name: 'Antariksh' },
  { id: 'm15', name: 'Ashish' },
  { id: 'm16', name: 'Divyansh' },
  { id: 'm17', name: 'Dvij' },
  { id: 'm18', name: 'Gaurav' },
  { id: 'm19', name: 'Harshit Agarwal' },
  { id: 'm20', name: 'Harshit Anand' },
  { id: 'm21', name: 'Harshita' },
  { id: 'm22', name: 'Ishan' },
  { id: 'm23', name: 'Jishnu' },
  { id: 'm24', name: 'Kavish' },
  { id: 'm25', name: 'Kinshuk' },
  { id: 'm26', name: 'Kshitij' },
  { id: 'm27', name: 'Mac' },
  { id: 'm28', name: 'Malav' },
  { id: 'm29', name: 'Mansi' },
  { id: 'm30', name: 'Mukati' },
  { id: 'm31', name: 'Onkar' },
  { id: 'm32', name: 'Oshin' },
  { id: 'm33', name: 'Pallavi' },
  { id: 'm34', name: 'Pawan' },
  { id: 'm35', name: 'Pranali' },
  { id: 'm36', name: 'Prashant' },
  { id: 'm37', name: 'Princy' },
  { id: 'm38', name: 'Rashi' },
  { id: 'm39', name: 'Richa' },
  { id: 'm40', name: 'Rohit' },
  { id: 'm41', name: 'Sahil' },
  { id: 'm42', name: 'Saket' },
  { id: 'm43', name: 'Saloni' },
  { id: 'm44', name: 'Sam' },
  { id: 'm45', name: 'Samriddhi' },
  { id: 'm46', name: 'Sanjana' },
  { id: 'm47', name: 'Saurabh' },
  { id: 'm48', name: 'Sawrav' },
  { id: 'm49', name: 'Shikha' },
  { id: 'm50', name: 'Shiva' },
  { id: 'm51', name: 'Shivam' },
  { id: 'm52', name: 'Shubham' },
  { id: 'm53', name: 'Sid' },
  { id: 'm54', name: 'Srikar' },
  { id: 'm55', name: 'Subhinav' },
  { id: 'm56', name: 'Sushant' },
  { id: 'm57', name: 'Taran' },
  { id: 'm58', name: 'Unaccounted' },
  { id: 'm59', name: 'Vedant' },
  { id: 'm60', name: 'Venkatesh' },
  { id: 'm61', name: 'Vij' },
  { id: 'm62', name: 'Vikas' },
  { id: 'm63', name: 'Vruttant' },
  { id: 'm64', name: 'Yash' },
  { id: 'm65', name: 'Yashvardhan' },
  { id: 'm66', name: 'Yatin' },
];

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });
  await initSchema();
  for (const m of INITIAL_MEMBERS) {
    await sql`INSERT INTO members (id, name) VALUES (${m.id}, ${m.name}) ON CONFLICT (id) DO NOTHING`;
  }
  return res.status(200).json({ ok: true, seeded: INITIAL_MEMBERS.length });
}
